apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "99999598-ingress"
spec:
  ingressClassName: ingress-internal
  rules:
  - host: "99999598.cepg-aa.kubepia.net"
    http:
      paths:
      - path: /
        backend:
          service:
            name: my-99999598
            port:
              number: 8080
        pathType: Prefix
